language: node_js

node_js : 
    - "0.10"
    - "0.11"

addons:
    postgresql: "9.3"

before_script:
  - psql -f test/createdb.sql -U postgres
  - psql -f test/postgres.sql -U postgres
  - mysql -e 'create database ee_orm_test_mysql;'